<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ViewSchedule.aspx.cs" Inherits="Flight_Reservation.Schedule.ViewSchedule" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <center>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="scheduleID" DataSourceID="SqlDataSource1" ForeColor="#333333" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="1300px" GridLines="None" >
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
           
            <asp:CommandField ShowSelectButton="True" />
           
            <asp:BoundField DataField="scheduleID" HeaderText="scheduleID" InsertVisible="False" ReadOnly="True" SortExpression="scheduleID" >
            </asp:BoundField>
            <asp:BoundField DataField="origin" HeaderText="origin" SortExpression="origin" >
            </asp:BoundField>
            <asp:BoundField DataField="departureDate" HeaderText="departureDate" SortExpression="departureDate" >
            </asp:BoundField>
            <asp:BoundField DataField="destination" HeaderText="destination" SortExpression="destination" >
            </asp:BoundField>
            <asp:BoundField DataField="departureTime" HeaderText="departureTime" SortExpression="departureTime" >
            </asp:BoundField>
            <asp:BoundField DataField="adultPrice" HeaderText="adultPrice" SortExpression="adultPrice" >
            </asp:BoundField>
            <asp:BoundField DataField="childPrice" HeaderText="childPrice" SortExpression="childPrice" >
            </asp:BoundField>
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>

        <br />

    <asp:Button ID="btnAddSchedule" runat="server" Text="Add Schedule" OnClick="btnAddSchedule_Click" />


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:flightdbConnectionString %>" SelectCommand="SELECT [scheduleID], [origin], [departureDate], [destination], [departureTime], [adultPrice], [childPrice] FROM [Schedule]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM Schedule WHERE (scheduleID = @original_scheduleID) AND (origin = @original_origin) AND (departureDate = @original_departureDate) AND (destination = @original_destination) AND (departureTime = @original_departureTime) AND (adultPrice = @original_adultPrice) AND (childPrice = @original_childPrice)" InsertCommand="INSERT INTO [Schedule] ([origin], [departureDate], [destination], [departureTime], [adultPrice], [childrenPrice]) VALUES (@origin, @departureDate, @destination, @departureTime, @adultPrice, @childPrice)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE Schedule SET origin = @origin, departureDate = @departureDate, destination = @destination, departureTime = @departureTime, adultPrice = @adultPrice, childPrice = @childPrice WHERE (scheduleID = @original_scheduleID) AND (origin = @original_origin) AND (departureDate = @original_departureDate) AND (destination = @original_destination) AND (departureTime = @original_departureTime) AND (adultPrice = @original_adultPrice) AND (childPrice = @original_childPrice)">
        <DeleteParameters>
            <asp:Parameter Name="original_scheduleID" Type="Int32" />
            <asp:Parameter Name="original_origin" Type="String" />
            <asp:Parameter Name="original_departureDate" Type="String" />
            <asp:Parameter Name="original_destination" Type="String" />
            <asp:Parameter Name="original_departureTime" Type="String" />
            <asp:Parameter Name="original_adultPrice" Type="Double" />
            <asp:Parameter Name="original_childPrice" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="origin" Type="String" />
            <asp:Parameter Name="departureDate" Type="String" />
            <asp:Parameter Name="destination" Type="String" />
            <asp:Parameter Name="departureTime" Type="String" />
            <asp:Parameter Name="adultPrice" Type="Double" />
            <asp:Parameter Name="childPrice" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="origin" Type="String" />
            <asp:Parameter Name="departureDate" Type="String" />
            <asp:Parameter Name="destination" Type="String" />
            <asp:Parameter Name="departureTime" Type="String" />
            <asp:Parameter Name="adultPrice" Type="Double" />
            <asp:Parameter Name="childPrice" />
            <asp:Parameter Name="original_scheduleID" Type="Int32" />
            <asp:Parameter Name="original_origin" Type="String" />
            <asp:Parameter Name="original_departureDate" Type="String" />
            <asp:Parameter Name="original_destination" Type="String" />
            <asp:Parameter Name="original_departureTime" Type="String" />
            <asp:Parameter Name="original_adultPrice" Type="Double" />
            <asp:Parameter Name="original_childPrice" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </center>

</asp:Content>